### PR TITLE
Remove special case for local environments

### PR DESCRIPTION
**Pull request by tjoelsson**
## Summary of changes

- Always load package named `nginx` (install from epel)
- Remove role dependency

## How to Test

Use in playbook by adding this to requirements file:

```
- src: git@github.com:tjoelsson/ansible-role-nginx
  scm: git
  name: juwai.nginx
  version: dcf47c3
```

### CODE REVIEW

**Comment by tjoelsson** [comment]
Changing this role because nginx16 package can no longer be found in webtatic repo. @mark-juwai @upbeta01 please review

**Review by mark-juwai — APPROVED** [review]
`nginx/1.6.3` installed with box `juwai-centos68`

**Review by upbeta01 — APPROVED** [review]
:+1: 

Just a heads-up. Since we are not pinning the `nginx` version, every time there will be changes on the vagrant box base (`juwai-centos68`) the nginx epel release might be different and this might have issue with libraries being used.

**Comment by tjoelsson** [comment]
@upbeta01 Thanks. If you have a suggestion for improving this role, feel free to PR.

**Pull request merged**
